import { Product, ProductStatus } from '../models/product.model';

export const productsMock: Product[] = [
  {
    id: 1,
    title: 'Fone de Ouvido Bluetooth',
    description: 'Fone de ouvido bluetooth com cancelamento de ruído, ótima qualidade de som. Usado apenas algumas vezes, em perfeito estado. Acompanha estojo de carregamento e cabo USB.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 1,
    userId: 1,
    ownerName: 'John Doe',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 3,
    acceptableExchanges: ['Smartwatch', 'Caixa de som portátil', 'Teclado mecânico'],
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2023-05-10'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 2,
    title: 'Kit de Maquiagem Novo',
    description: 'Kit completo de maquiagem com paleta de sombras, batons, blush e pincéis. Todas as cores são neutras e combinam com qualquer tom de pele. Produto novo, apenas aberto para verificação.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 2,
    userId: 2,
    ownerName: 'Maria Santos',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 4,
    acceptableExchanges: ['Perfumes', 'Produtos para cabelo', 'Acessórios femininos'],
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2023-05-15'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 3,
    title: 'Relógio de Pulso',
    description: 'Relógio analógico masculino, pulseira de couro legítimo na cor marrom. Mostrador em preto com detalhes prateados. Usado poucas vezes, está em excelente estado. Acompanha caixa original.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 3,
    userId: 3,
    ownerName: 'Pedro Silva',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 2,
    acceptableExchanges: ['Óculos de sol', 'Fone de ouvido', 'Smartwatch'],
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2023-05-20'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 4,
    title: 'Caderno de Anotações',
    description: 'Caderno capa dura com 200 folhas sem pauta, ideal para desenhos e anotações. Capa em couro sintético na cor azul marinho. Novo, ainda na embalagem original.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 4,
    userId: 4,
    ownerName: 'Ana Martins',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 1,
    acceptableExchanges: ['Canetas', 'Livros', 'Marca-textos'],
    createdAt: new Date('2023-05-22'),
    updatedAt: new Date('2023-05-22'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 5,
    title: 'Raquete de Tênis',
    description: 'Raquete de tênis profissional, pouco usada. Encordoamento em perfeito estado. Acompanha capa protetora. Ideal para jogadores intermediários.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 5,
    userId: 1,
    ownerName: 'John Doe',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 3,
    acceptableExchanges: ['Bola de basquete', 'Luvas de boxe', 'Kettlebell'],
    createdAt: new Date('2023-05-25'),
    updatedAt: new Date('2023-05-25'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 6,
    title: 'Vestido de Festa',
    description: 'Vestido longo de festa, cor verde esmeralda, tamanho M. Usado apenas uma vez, está em perfeito estado. Tecido em cetim com detalhes em renda. Ideal para ocasiões especiais.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 6,
    userId: 2,
    ownerName: 'Maria Santos',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 4,
    acceptableExchanges: ['Bolsa de festa', 'Sapatos femininos', 'Acessórios'],
    createdAt: new Date('2023-05-27'),
    updatedAt: new Date('2023-05-27'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 7,
    title: 'Câmera Digital',
    description: 'Câmera digital compacta com 16MP, zoom óptico de 10x e estabilizador de imagem. Usada, mas em perfeito estado de conservação. Acompanha carregador, bateria extra e cartão de memória de 32GB.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 1,
    userId: 3,
    ownerName: 'Pedro Silva',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 2,
    acceptableExchanges: ['Tablet', 'Tripé para câmera', 'Fone de ouvido bluetooth'],
    createdAt: new Date('2023-05-30'),
    updatedAt: new Date('2023-05-30'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 8,
    title: 'Kit de Skincare',
    description: 'Kit completo de skincare contendo limpador facial, tônico, sérum de vitamina C e hidratante facial. Produtos novos, apenas o hidratante foi usado uma vez para teste.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 2,
    userId: 4,
    ownerName: 'Ana Martins',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 1,
    acceptableExchanges: ['Maquiagem', 'Perfumes', 'Produtos para cabelo'],
    createdAt: new Date('2023-06-02'),
    updatedAt: new Date('2023-06-02'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 9,
    title: 'Óculos de Sol',
    description: 'Óculos de sol unissex, armação em acetato preto e lentes polarizadas. Proteção UV400. Usado poucas vezes, sem arranhões. Acompanha case protetor e flanela para limpeza.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 3,
    userId: 1,
    ownerName: 'John Doe',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 3,
    acceptableExchanges: ['Relógio', 'Bolsa', 'Carteira em couro'],
    createdAt: new Date('2023-06-05'),
    updatedAt: new Date('2023-06-05'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 10,
    title: 'Luminária de Mesa',
    description: 'Luminária de mesa articulada, estrutura em metal na cor preta com acabamento fosco. Ideal para escritório ou mesa de estudos. Em perfeito estado de funcionamento.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 4,
    userId: 2,
    ownerName: 'Maria Santos',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 4,
    acceptableExchanges: ['Organizadores de mesa', 'Porta-canetas', 'Agenda'],
    createdAt: new Date('2023-06-08'),
    updatedAt: new Date('2023-06-08'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 11,
    title: 'Tênis para Corrida',
    description: 'Tênis específico para corrida, tamanho 42, cor cinza com detalhes em verde. Usado apenas duas vezes, está como novo. Amortecimento de alto desempenho, ideal para corridas longas.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 5,
    userId: 5,
    ownerName: 'Lucas Oliveira',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 2,
    acceptableExchanges: ['Camiseta esportiva', 'Bermuda fitness', 'Garrafa térmica'],
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-06-10'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 12,
    title: 'Jaqueta Jeans',
    description: 'Jaqueta jeans masculina, tamanho G, lavagem média. Usada poucas vezes, está em ótimo estado. Modelo clássico, combina com diversas ocasiões.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 6,
    userId: 5,
    ownerName: 'Lucas Oliveira',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 2,
    acceptableExchanges: ['Camiseta', 'Calça jeans', 'Tênis casual'],
    createdAt: new Date('2023-06-12'),
    updatedAt: new Date('2023-06-12'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 13,
    title: 'Tablet 10 polegadas',
    description: 'Tablet Android com tela de 10 polegadas, 64GB de armazenamento, 4GB de RAM. Usado por 6 meses, sem arranhões ou marcas de uso. Acompanha carregador original e capa protetora.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 1,
    userId: 6,
    ownerName: 'Carolina Ferreira',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 3,
    acceptableExchanges: ['Fone de ouvido bluetooth', 'Smartwatch', 'E-reader'],
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15'),
    status: ProductStatus.AVAILABLE
  },
  {
    id: 14,
    title: 'Kit Pincéis de Maquiagem',
    description: 'Kit com 12 pincéis profissionais para maquiagem. Cerdas sintéticas de alta qualidade, cabo em madeira. Usados poucas vezes, estão em excelente estado. Acompanha estojo.',
    imageUrl: 'assets/images/placeholder.svg',
    categoryId: 2,
    userId: 6,
    ownerName: 'Carolina Ferreira',
    ownerAvatar: 'assets/images/placeholder.svg',
    ownerReputationLevel: 3,
    acceptableExchanges: ['Paleta de sombras', 'Batom', 'Produtos para sobrancelha'],
    createdAt: new Date('2023-06-18'),
    updatedAt: new Date('2023-06-18'),
    status: ProductStatus.RESERVED
  }
];
