import { Proposal, ProposalStatus } from '../models/proposal.model';

export const proposalsMock: Proposal[] = [
  {
    id: 1,
    productOfferedId: 3,
    productOfferedTitle: 'Relógio de Pulso',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 1,
    productRequestedTitle: 'Fone de Ouvido Bluetooth',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 3,
    fromUserName: 'Pedro Silva',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 2,
    toUserId: 1,
    toUserName: 'John Doe',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 3,
    message: 'Olá John! Estou interessado no seu fone de ouvido. Meu relógio está em ótimo estado e acho que seria uma troca justa. O que você acha?',
    status: ProposalStatus.PENDING,
    created_at: new Date('2023-06-20'),
    updated_at: new Date('2023-06-20')
  },
  {
    id: 2,
    productOfferedId: 8,
    productOfferedTitle: 'Kit de Skincare',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 2,
    productRequestedTitle: 'Kit de Maquiagem Novo',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 4,
    fromUserName: 'Ana Martins',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 1,
    toUserId: 2,
    toUserName: 'Maria Santos',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 4,
    message: 'Oi Maria! Adorei seu kit de maquiagem e gostaria de propor uma troca pelo meu kit de skincare. Os produtos são de ótima qualidade e combinam muito com maquiagem.',
    status: ProposalStatus.ACCEPTED,
    created_at: new Date('2023-06-22'),
    updated_at: new Date('2023-06-23')
  },
  {
    id: 3,
    productOfferedId: 5,
    productOfferedTitle: 'Raquete de Tênis',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 11,
    productRequestedTitle: 'Tênis para Corrida',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 1,
    fromUserName: 'John Doe',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 3,
    toUserId: 5,
    toUserName: 'Lucas Oliveira',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 2,
    message: 'Olá Lucas! Vi que você tem um tênis para corrida e gostaria de propor uma troca pela minha raquete de tênis que está em excelente estado. Sou tenista amador e estou mudando para corrida agora.',
    status: ProposalStatus.REJECTED,
    created_at: new Date('2023-06-25'),
    updated_at: new Date('2023-06-26')
  },
  {
    id: 4,
    productOfferedId: 10,
    productOfferedTitle: 'Luminária de Mesa',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 4,
    productRequestedTitle: 'Caderno de Anotações',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 2,
    fromUserName: 'Maria Santos',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 4,
    toUserId: 4,
    toUserName: 'Ana Martins',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 1,
    message: 'Oi Ana! Adorei seu caderno de anotações e gostaria de propor uma troca pela minha luminária de mesa. Ela é articulada e perfeita para estudos e leitura!',
    status: ProposalStatus.COMPLETED,
    created_at: new Date('2023-06-28'),
    updated_at: new Date('2023-06-30')
  },
  {
    id: 5,
    productOfferedId: 12,
    productOfferedTitle: 'Jaqueta Jeans',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 6,
    productRequestedTitle: 'Vestido de Festa',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 5,
    fromUserName: 'Lucas Oliveira',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 2,
    toUserId: 2,
    toUserName: 'Maria Santos',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 4,
    message: 'Olá Maria! Minha namorada se interessou pelo seu vestido de festa e gostaria de oferecer minha jaqueta jeans em troca. Ela está em perfeito estado e é de marca.',
    status: ProposalStatus.PENDING,
    created_at: new Date('2023-07-02'),
    updated_at: new Date('2023-07-02')
  },
  {
    id: 6,
    productOfferedId: 13,
    productOfferedTitle: 'Tablet 10 polegadas',
    productOfferedImageUrl: 'assets/images/placeholder.svg',
    productRequestedId: 7,
    productRequestedTitle: 'Câmera Digital',
    productRequestedImageUrl: 'assets/images/placeholder.svg',
    fromUserId: 6,
    fromUserName: 'Carolina Ferreira',
    fromUserAvatar: 'assets/images/placeholder.svg',
    fromUserReputationLevel: 3,
    toUserId: 3,
    toUserName: 'Pedro Silva',
    toUserAvatar: 'assets/images/placeholder.svg',
    toUserReputationLevel: 2,
    message: 'Olá Pedro! Estou interessada na sua câmera digital e gostaria de propor uma troca pelo meu tablet. O tablet está em perfeito estado, com poucos meses de uso.',
    status: ProposalStatus.ACCEPTED,
    created_at: new Date('2023-07-05'),
    updated_at: new Date('2023-07-06')
  }
];
